// 部编版四年级上册 1-8单元 看拼音写词语
const VOCABULARY = [
  // 第一单元
  { unit: 1, pinyin: 'kuān kuò', word: '宽阔', hint: '江面很___' },
  { unit: 1, pinyin: 'bó wù', word: '薄雾', hint: '早晨的___' },
  { unit: 1, pinyin: 'lǒng zhào', word: '笼罩', hint: '大雾___着江面' },
  { unit: 1, pinyin: 'fèi téng', word: '沸腾', hint: '人声___' },
  { unit: 1, pinyin: 'bēn téng', word: '奔腾', hint: '江水___' },
  { unit: 1, pinyin: 'yī jiù', word: '依旧', hint: '___壮观' },
  { unit: 1, pinyin: 'huī fù', word: '恢复', hint: '___平静' },
  { unit: 1, pinyin: 'càn làn', word: '灿烂', hint: '阳光___' },
  { unit: 1, pinyin: 'zhú gān', word: '竹竿', hint: '撑着___' },
  { unit: 1, pinyin: 'guī lǜ', word: '规律', hint: '自然的___' },
  { unit: 1, pinyin: 'fèng xì', word: '缝隙', hint: '石头的___' },
  { unit: 1, pinyin: 'zhào yào', word: '照耀', hint: '阳光___' },
  { unit: 1, pinyin: 'shù shāo', word: '树梢', hint: '高高的___' },
  { unit: 1, pinyin: 'jìng jì', word: '静寂', hint: '十分___' },
  { unit: 1, pinyin: 'bái máng máng', word: '白茫茫', hint: '___的一片' },
  { unit: 1, pinyin: 'ruò yǐn ruò xiàn', word: '若隐若现', hint: '远处___' },
  { unit: 1, pinyin: 'áng shǒu dōng wàng', word: '昂首东望', hint: '___等着' },
  { unit: 1, pinyin: 'fēng píng làng jìng', word: '风平浪静', hint: '海面___' },
  { unit: 1, pinyin: 'shuǐ tiān xiāng jiē', word: '水天相接', hint: '远处___' },
  { unit: 1, pinyin: 'héng guàn jiāng miàn', word: '横贯江面', hint: '___而来' },
  { unit: 1, pinyin: 'qí tóu bìng jìn', word: '齐头并进', hint: '___地冲来' },
  { unit: 1, pinyin: 'màn tiān juǎn dì', word: '漫天卷地', hint: '___地涌来' },
  { unit: 1, pinyin: 'chàn dòng', word: '颤动', hint: '微微___' },
  { unit: 1, pinyin: 'shà shí', word: '霎时', hint: '___间' },
  { unit: 1, pinyin: 'fàn wéi', word: '范围', hint: '活动___' },
  { unit: 1, pinyin: 'huā suì', word: '花穗', hint: '稻子的___' },
  { unit: 1, pinyin: 'zhǎng cháo', word: '涨潮', hint: '海水___' },
  { unit: 1, pinyin: 'róng shù', word: '榕树', hint: '大___' },
  { unit: 1, pinyin: 'zhèn jìng', word: '镇静', hint: '保持___' },
  { unit: 1, pinyin: 'lí huáng', word: '梨黄', hint: '___的叶子' },
  { unit: 1, pinyin: 'zǐ hóng', word: '紫红', hint: '___的花' },
  { unit: 1, pinyin: 'jīn càn càn', word: '金灿灿', hint: '___的稻田' },
  { unit: 1, pinyin: 'xiào yíng yíng', word: '笑盈盈', hint: '___的脸' },
  { unit: 1, pinyin: 'rén shēng dǐng fèi', word: '人声鼎沸', hint: '___' },
  { unit: 1, pinyin: 'shān bēng dì liè', word: '山崩地裂', hint: '___的响声' },
  { unit: 1, pinyin: 'bù róng zhì yí', word: '不容置疑', hint: '___的事实' },
  { unit: 1, pinyin: 'shén mì mò cè', word: '神秘莫测', hint: '___的峡谷' },
  { unit: 1, pinyin: 'shén lái zhī bǐ', word: '神来之笔', hint: '堪称___' },
  { unit: 1, pinyin: 'qiān zī bǎi tài', word: '千姿百态', hint: '___的石头' },
  { unit: 1, pinyin: 'rén jì hǎn zhì', word: '人迹罕至', hint: '___的地方' },
  { unit: 1, pinyin: 'yìng jiē bù xiá', word: '应接不暇', hint: '___' },
  { unit: 1, pinyin: 'juān juān xì liú', word: '涓涓细流', hint: '___' },
  { unit: 1, pinyin: 'lián lián fēi pù', word: '连连飞瀑', hint: '___' },
  { unit: 1, pinyin: 'tāo tāo jiāng shuǐ', word: '滔滔江水', hint: '___' },
  { unit: 1, pinyin: 'yù yù cāng cāng', word: '郁郁苍苍', hint: '___的树木' },
  { unit: 1, pinyin: 'huǎng huǎng hū hū', word: '恍恍惚惚', hint: '___的' },
  { unit: 1, pinyin: 'fēn fāng yù yù', word: '芬芳馥郁', hint: '___的花香' },
  { unit: 1, pinyin: 'zǐ tán sè', word: '紫檀色', hint: '___的' },
  { unit: 1, pinyin: 'bǎi hé sè', word: '百合色', hint: '___的' },
  { unit: 1, pinyin: 'pú táo huī', word: '葡萄灰', hint: '___的' },
  { unit: 1, pinyin: 'qié zi zǐ', word: '茄子紫', hint: '___的' },

  // 第二单元
  { unit: 2, pinyin: 'jūn yún', word: '均匀', hint: '分布___' },
  { unit: 2, pinyin: 'chóng dié', word: '重叠', hint: '层层___' },
  { unit: 2, pinyin: 'kòng xì', word: '空隙', hint: '叶子的___' },
  { unit: 2, pinyin: 'yè bǐng', word: '叶柄', hint: '连接叶子的___' },
  { unit: 2, pinyin: 'chù jiǎo', word: '触角', hint: '蜗牛的___' },
  { unit: 2, pinyin: 'hén jì', word: '痕迹', hint: '留下___' },
  { unit: 2, pinyin: 'zhú jiàn', word: '逐渐', hint: '___变大' },
  { unit: 2, pinyin: 'xiū xiǎng', word: '休想', hint: '___碰到' },
  { unit: 2, pinyin: 'zhù zhái', word: '住宅', hint: '蟋蟀的___' },
  { unit: 2, pinyin: 'yǐn bì', word: '隐蔽', hint: '___起来' },
  { unit: 2, pinyin: 'yǐn cáng', word: '隐藏', hint: '___在草丛' },
  { unit: 2, pinyin: 'xuǎn zé', word: '选择', hint: '___地址' },
  { unit: 2, pinyin: 'zhù zhǐ', word: '住址', hint: '蟋蟀的___' },
  { unit: 2, pinyin: 'dòng xué', word: '洞穴', hint: '动物的___' },
  { unit: 2, pinyin: 'róu ruò', word: '柔弱', hint: '___的枝条' },
  { unit: 2, pinyin: 'sōu suǒ', word: '搜索', hint: '___食物' },
  { unit: 2, pinyin: 'qīng xié', word: '倾斜', hint: '___的坡' },
  { unit: 2, pinyin: 'píng tǎn', word: '平坦', hint: '___的路' },
  { unit: 2, pinyin: 'bā tǔ', word: '扒土', hint: '蟋蟀___' },
  { unit: 2, pinyin: 'kuān chǎng', word: '宽敞', hint: '___的客厅' },
  { unit: 2, pinyin: 'yǐn rén zhù yì', word: '引人注意', hint: '___' },
  { unit: 2, pinyin: 'háo bù kě xī', word: '毫不可惜', hint: '___' },
  { unit: 2, pinyin: 'suí yù ér ān', word: '随遇而安', hint: '___' },
  { unit: 2, pinyin: 'zuò wò bù ān', word: '坐卧不安', hint: '___' },
  { unit: 2, pinyin: 'xiāo mó shí guāng', word: '消磨时光', hint: '___' },
  { unit: 2, pinyin: 'bù kě sī yì', word: '不可思议', hint: '___' },
  { unit: 2, pinyin: 'jīng shén dà zhèn', word: '精神大振', hint: '___' },
  { unit: 2, pinyin: 'wǎng fèi xīn jī', word: '枉费心机', hint: '___' },
  { unit: 2, pinyin: 'hào rú yān hǎi', word: '浩如烟海', hint: '___' },

  // 第三单元
  { unit: 3, pinyin: 'yáng yì', word: '洋溢', hint: '___着笑声' },
  { unit: 3, pinyin: 'yǔn xǔ', word: '允许', hint: '___进入' },
  { unit: 3, pinyin: 'wéi qiáng', word: '围墙', hint: '高高的___' },
  { unit: 3, pinyin: 'lóng dōng', word: '隆冬', hint: '___时节' },
  { unit: 3, pinyin: 'gū dú', word: '孤独', hint: '十分___' },
  { unit: 3, pinyin: 'xùn chì', word: '训斥', hint: '大声___' },
  { unit: 3, pinyin: 'fù gài', word: '覆盖', hint: '白雪___' },
  { unit: 3, pinyin: 'níng shì', word: '凝视', hint: '___着' },
  { unit: 3, pinyin: 'lěng kù', word: '冷酷', hint: '___的目光' },
  { unit: 3, pinyin: 'yú kuài', word: '愉快', hint: '___地玩耍' },
  { unit: 3, pinyin: 'chāi chú', word: '拆除', hint: '___围墙' },
  { unit: 3, pinyin: 'shèng xià', word: '剩下', hint: '___的' },
  { unit: 3, pinyin: 'fá mù', word: '伐木', hint: '___工人' },
  { unit: 3, pinyin: 'gào shì pái', word: '告示牌', hint: '花园的___' },
  { unit: 3, pinyin: 'huǒ là là', word: '火辣辣', hint: '___的太阳' },
  { unit: 3, pinyin: 'méi yóu dēng', word: '煤油灯', hint: '___的光' },
  { unit: 3, pinyin: 'xiān huā shèng kāi', word: '鲜花盛开', hint: '___' },
  { unit: 3, pinyin: 'lǜ shù chéng yīn', word: '绿树成荫', hint: '___' },
  { unit: 3, pinyin: 'xiān guǒ piāo xiāng', word: '鲜果飘香', hint: '___' },
  { unit: 3, pinyin: 'kuáng fēng dà zuò', word: '狂风大作', hint: '___' },
  { unit: 3, pinyin: 'xuě huā fēi wǔ', word: '雪花飞舞', hint: '___' },
  { unit: 3, pinyin: 'cǎo cuì huā kāi', word: '草翠花开', hint: '___' },
  { unit: 3, pinyin: 'bèng bèng tiào tiào', word: '蹦蹦跳跳', hint: '___' },
  { unit: 3, pinyin: 'kě lián bā bā', word: '可怜巴巴', hint: '___' },
  { unit: 3, pinyin: 'qín qín kěn kěn', word: '勤勤恳恳', hint: '___' },
  { unit: 3, pinyin: 'kū zhī bài yè', word: '枯枝败叶', hint: '___' },

  // 第四单元
  { unit: 4, pinyin: 'gāo ào', word: '高傲', hint: '___的白鹅' },
  { unit: 4, pinyin: 'zhèng zhòng', word: '郑重', hint: '___地说' },
  { unit: 4, pinyin: 'jīng jù', word: '京剧', hint: '看___' },
  { unit: 4, pinyin: 'zī wèi', word: '滋味', hint: '品尝___' },
  { unit: 4, pinyin: 'tǎng ruò', word: '倘若', hint: '___有危险' },
  { unit: 4, pinyin: 'shì hòu', word: '侍候', hint: '___主人' },
  { unit: 4, pinyin: 'pí qì', word: '脾气', hint: '坏___' },
  { unit: 4, pinyin: 'zé bèi', word: '责备', hint: '受到___' },
  { unit: 4, pinyin: 'lín jìn', word: '邻近', hint: '___的村子' },
  { unit: 4, pinyin: 'xìng gé', word: '性格', hint: '温和的___' },
  { unit: 4, pinyin: 'rèn píng', word: '任凭', hint: '___风吹' },
  { unit: 4, pinyin: 'tān wán', word: '贪玩', hint: '___的小猫' },
  { unit: 4, pinyin: 'jìn zhí', word: '尽职', hint: '___地守着' },
  { unit: 4, pinyin: 'zhǐ gǎo', word: '纸稿', hint: '铺在___上' },
  { unit: 4, pinyin: 'méi huā', word: '梅花', hint: '___脚印' },
  { unit: 4, pinyin: 'diē dǎo', word: '跌倒', hint: '不小心___' },
  { unit: 4, pinyin: 'kāi pì', word: '开辟', hint: '___新路' },
  { unit: 4, pinyin: 'jú cù', word: '局促', hint: '___不安' },
  { unit: 4, pinyin: 'háo bù xiāng ràng', word: '毫不相让', hint: '___' },
  { unit: 4, pinyin: 'yī rì sān cān', word: '一日三餐', hint: '___' },
  { unit: 4, pinyin: 'cóng róng bù pò', word: '从容不迫', hint: '___' },
  { unit: 4, pinyin: 'yáng cháng ér qù', word: '扬长而去', hint: '___' },
  { unit: 4, pinyin: 'kōng kōng rú yě', word: '空空如也', hint: '___' },
  { unit: 4, pinyin: 'gōng yǎng bù zhōu', word: '供养不周', hint: '___' },
  { unit: 4, pinyin: 'bù shèng qí fán', word: '不胜其烦', hint: '___' },
  { unit: 4, pinyin: 'jià zi shí zú', word: '架子十足', hint: '___' },
  { unit: 4, pinyin: 'bǐng xī', word: '屏息', hint: '___凝视' },
  { unit: 4, pinyin: 'níng shì', word: '凝视', hint: '___着' },
  { unit: 4, pinyin: 'biàn huà duō duān', word: '变化多端', hint: '___' },
  { unit: 4, pinyin: 'zhī shé huā luò', word: '枝折花落', hint: '___' },
  { unit: 4, pinyin: 'yǐn háng dà jiào', word: '引吭大叫', hint: '___' },
  { unit: 4, pinyin: 'màn tiáo sī lǐ', word: '慢条斯理', hint: '___' },
  { unit: 4, pinyin: 'zì yóu zì zài', word: '自由自在', hint: '___' },
  { unit: 4, pinyin: 'shēng qì bó bó', word: '生气勃勃', hint: '___' },
  { unit: 4, pinyin: 'rú yuàn rú sù', word: '如怨如诉', hint: '___' },
  { unit: 4, pinyin: 'chèn qí bù bèi', word: '趁其不备', hint: '___' },

  // 第五单元
  { unit: 5, pinyin: 'pán xuán', word: '盘旋', hint: '在空中___' },
  { unit: 5, pinyin: 'chéng zhuān', word: '城砖', hint: '___砌成' },
  { unit: 5, pinyin: 'chéng qiáng', word: '城墙', hint: '高高的___' },
  { unit: 5, pinyin: 'tún bīng', word: '屯兵', hint: '___驻守' },
  { unit: 5, pinyin: 'bǎo lěi', word: '堡垒', hint: '坚固的___' },
  { unit: 5, pinyin: 'dǎ zhàng', word: '打仗', hint: '去___' },
  { unit: 5, pinyin: 'hū yìng', word: '呼应', hint: '前后___' },
  { unit: 5, pinyin: 'jiān bǎng', word: '肩膀', hint: '___上' },
  { unit: 5, pinyin: 'zhì huì', word: '智慧', hint: '劳动人民的___' },
  { unit: 5, pinyin: 'níng jié', word: '凝结', hint: '___着' },
  { unit: 5, pinyin: 'cháng láng', word: '长廊', hint: '颐和园的___' },
  { unit: 5, pinyin: 'zhù zi', word: '柱子', hint: '红色的___' },
  { unit: 5, pinyin: 'jiàn zhù', word: '建筑', hint: '古老的___' },
  { unit: 5, pinyin: 'gōng diàn', word: '宫殿', hint: '金碧辉煌的___' },
  { unit: 5, pinyin: 'cōng yù', word: '葱郁', hint: '___的树' },
  { unit: 5, pinyin: 'yǎn yìng', word: '掩映', hint: '绿树___' },
  { unit: 5, pinyin: 'zhū hóng', word: '朱红', hint: '___的柱子' },
  { unit: 5, pinyin: 'dī àn', word: '堤岸', hint: '湖边的___' },
  { unit: 5, pinyin: 'diāo kè', word: '雕刻', hint: '精美的___' },
  { unit: 5, pinyin: 'shī zi', word: '狮子', hint: '石___' },
  { unit: 5, pinyin: 'fó xiāng gé', word: '佛香阁', hint: '___' },
  { unit: 5, pinyin: 'qì pò', word: '气魄', hint: '雄伟的___' },
  { unit: 5, pinyin: 'xióng wěi', word: '雄伟', hint: '___的长城' },
  { unit: 5, pinyin: 'jīn bì huī huáng', word: '金碧辉煌', hint: '___' },
  { unit: 5, pinyin: 'shén qīng qì shuǎng', word: '神清气爽', hint: '___' },
  { unit: 5, pinyin: 'yǐn yǐn yuē yuē', word: '隐隐约约', hint: '___' },
  { unit: 5, pinyin: 'zī tài bù yī', word: '姿态不一', hint: '___' },
  { unit: 5, pinyin: 'chóng shān jùn lǐng', word: '崇山峻岭', hint: '___' },
  { unit: 5, pinyin: 'jǔ shì wú shuāng', word: '举世无双', hint: '___' },
  { unit: 5, pinyin: 'xiǎng yù shì jiè', word: '享誉世界', hint: '___' },
  { unit: 5, pinyin: 'shēn cái kuí wǔ', word: '身材魁梧', hint: '___' },
  { unit: 5, pinyin: 'shén tài zì ruò', word: '神态自若', hint: '___' },
  { unit: 5, pinyin: 'jiǔ jīng shā chǎng', word: '久经沙场', hint: '___' },
  { unit: 5, pinyin: 'nán zhēng běi zhàn', word: '南征北战', hint: '___' },
  { unit: 5, pinyin: 'suǒ xiàng pī mǐ', word: '所向披靡', hint: '___' },
  { unit: 5, pinyin: 'yuè yuè yù shì', word: '跃跃欲试', hint: '___' },
  { unit: 5, pinyin: 'ruò yǒu suǒ sī', word: '若有所思', hint: '___' },
  { unit: 5, pinyin: 'shū sǐ pīn bó', word: '殊死拼搏', hint: '___' },

  // 第六单元
  { unit: 6, pinyin: 'jiàn gé', word: '间隔', hint: '时间___' },
  { unit: 6, pinyin: 'lǎn duò', word: '懒惰', hint: '___的猫' },
  { unit: 6, pinyin: 'sú yǔ', word: '俗语', hint: '民间___' },
  { unit: 6, pinyin: 'píng héng', word: '平衡', hint: '保持___' },
  { unit: 6, pinyin: 'lián jié', word: '联结', hint: '紧密___' },
  { unit: 6, pinyin: 'zàn tíng', word: '暂停', hint: '___一下' },
  { unit: 6, pinyin: 'kuà yuè', word: '跨越', hint: '___海峡' },
  { unit: 6, pinyin: 'hǎi xiá', word: '海峡', hint: '台湾___' },
  { unit: 6, pinyin: 'guì shù', word: '桂树', hint: '___开花' },
  { unit: 6, pinyin: 'cāng bái', word: '苍白', hint: '___的脸' },
  { unit: 6, pinyin: 'hóng rùn', word: '红润', hint: '___的脸蛋' },
  { unit: 6, pinyin: 'kuàng kuàng', word: '空旷', hint: '___的田野' },
  { unit: 6, pinyin: 'yí zhí xìng', word: '一致性', hint: '保持___' },
  { unit: 6, pinyin: 'yùn tái', word: '云台', hint: '___' },
  { unit: 6, pinyin: 'wān xí', word: '湾溪', hint: '___' },
  { unit: 6, pinyin: 'qī dài', word: '期待', hint: '满怀___' },
  { unit: 6, pinyin: 'shān hóng bào fā', word: '山洪暴发', hint: '___' },
  { unit: 6, pinyin: 'qīng bō yàng yàng', word: '清波漾漾', hint: '___' },
  { unit: 6, pinyin: 'xuè mài qīn qíng', word: '血脉亲情', hint: '___' },
  { unit: 6, pinyin: 'lǐ suǒ dāng rán', word: '理所当然', hint: '___' },
  { unit: 6, pinyin: 'tán hé róng yì', word: '谈何容易', hint: '___' },
  { unit: 6, pinyin: 'píng ān wú shì', word: '平安无事', hint: '___' },
  { unit: 6, pinyin: 'tū rú qí lái', word: '突如其来', hint: '___' },
  { unit: 6, pinyin: 'gǔ ròu tóng bāo', word: '骨肉同胞', hint: '___' },
  { unit: 6, pinyin: 'rén yǐng chuò chuò', word: '人影绰绰', hint: '___' },
  { unit: 6, pinyin: 'háo táo dà kū', word: '嚎啕大哭', hint: '___' },
  { unit: 6, pinyin: 'huǎng rán dà wù', word: '恍然大悟', hint: '___' },
  { unit: 6, pinyin: 'xié tiáo yǒu xù', word: '协调有序', hint: '___' },

  // 第七单元
  { unit: 7, pinyin: 'bó fù', word: '伯父', hint: '___鲁迅先生' },
  { unit: 7, pinyin: 'mó fàn', word: '模范', hint: '学习的___' },
  { unit: 7, pinyin: 'xún jǐng', word: '巡警', hint: '___先生' },
  { unit: 7, pinyin: 'chǎo rǎng', word: '吵嚷', hint: '大声___' },
  { unit: 7, pinyin: 'chéng chǔ', word: '惩处', hint: '受到___' },
  { unit: 7, pinyin: 'bào fù', word: '抱负', hint: '远大的___' },
  { unit: 7, pinyin: 'xiōng huái', word: '胸怀', hint: '广阔的___' },
  { unit: 7, pinyin: 'hè cǎi', word: '喝彩', hint: '大声___' },
  { unit: 7, pinyin: 'tuī jiàn', word: '推荐', hint: '___好书' },
  { unit: 7, pinyin: 'yǎn lián', word: '眼帘', hint: '映入___' },
  { unit: 7, pinyin: 'shān diào', word: '删掉', hint: '___一个字' },
  { unit: 7, pinyin: 'guī fàn', word: '规范', hint: '书写___' },
  { unit: 7, pinyin: 'zào rè', word: '燥热', hint: '___的天气' },
  { unit: 7, pinyin: 'róng qià', word: '融洽', hint: '___相处' },
  { unit: 7, pinyin: 'huáng hūn', word: '黄昏', hint: '___时分' },
  { unit: 7, pinyin: 'kè tīng', word: '客厅', hint: '在___里' },
  { unit: 7, pinyin: 'dì guó zhǔ yì', word: '帝国主义', hint: '___' },
  { unit: 7, pinyin: 'dēng hóng jiǔ lǜ', word: '灯红酒绿', hint: '___' },
  { unit: 7, pinyin: 'rè nào fēi fán', word: '热闹非凡', hint: '___' },
  { unit: 7, pinyin: 'fēng hé rì lì', word: '风和日丽', hint: '___' },
  { unit: 7, pinyin: 'yào wǔ yáng wēi', word: '耀武扬威', hint: '___' },
  { unit: 7, pinyin: 'dé yì yáng yáng', word: '得意洋洋', hint: '___' },
  { unit: 7, pinyin: 'zhèn xīng zhōng huá', word: '振兴中华', hint: '___' },
  { unit: 7, pinyin: 'jīn pí lì jìn', word: '筋疲力尽', hint: '___' },
  { unit: 7, pinyin: 'háo mǎ', word: '豪迈', hint: '___的气概' },
  { unit: 7, pinyin: 'xíng dān yǐng zhī', word: '形单影只', hint: '___' },
  { unit: 7, pinyin: 'nán yǔ gòng shòu', word: '难与共守', hint: '___' },
  { unit: 7, pinyin: 'yì fěi qiǎn nián', word: '遗臭万年', hint: '___' },
  { unit: 7, pinyin: 'nián shào qì shèng', word: '年少气盛', hint: '___' },
  { unit: 7, pinyin: 'kēng qiāng yǒu lì', word: '铿锵有力', hint: '___' },
  { unit: 7, pinyin: 'hé mù xiāng chǔ', word: '和睦相处', hint: '___' },
  { unit: 7, pinyin: 'nián yú gǔ xī', word: '年逾古稀', hint: '___' },

  // 第八单元
  { unit: 8, pinyin: 'gǎi guān', word: '改观', hint: '大为___' },
  { unit: 8, pinyin: 'chéng dù', word: '程度', hint: '严重的___' },
  { unit: 8, pinyin: 'yī lài', word: '依赖', hint: '___科技' },
  { unit: 8, pinyin: 'jì tuō', word: '寄托', hint: '___希望' },
  { unit: 8, pinyin: 'huàn xiǎng', word: '幻想', hint: '美好的___' },
  { unit: 8, pinyin: 'dòng chá', word: '洞察', hint: '___一切' },
  { unit: 8, pinyin: 'lián xì', word: '联系', hint: '保持___' },
  { unit: 8, pinyin: 'kǒng lóng', word: '恐龙', hint: '远古___' },
  { unit: 8, pinyin: 'xiōng měng', word: '凶猛', hint: '___的野兽' },
  { unit: 8, pinyin: 'gē zi', word: '鸽子', hint: '白色的___' },
  { unit: 8, pinyin: 'miáo huì', word: '描绘', hint: '___未来' },
  { unit: 8, pinyin: 'qīng yíng', word: '轻盈', hint: '___的步伐' },
  { unit: 8, pinyin: 'mǐn jié', word: '敏捷', hint: '动作___' },
  { unit: 8, pinyin: 'yīn tè', word: '因特', hint: '___网' },
  { unit: 8, pinyin: 'wǎng', word: '网', hint: '互联___' },
  { unit: 8, pinyin: 'yuán zǐ', word: '原子', hint: '___弹' },
  { unit: 8, pinyin: 'hé zhé', word: '哲学', hint: '___家' },
  { unit: 8, pinyin: 'xué jiā', word: '学家', hint: '科学___' },
  { unit: 8, pinyin: 'hū fēng huàn yǔ', word: '呼风唤雨', hint: '___' },
  { unit: 8, pinyin: 'chū hū yì liào', word: '出乎意料', hint: '___' },
  { unit: 8, pinyin: 'nóng gēng shè huì', word: '农耕社会', hint: '___' },
  { unit: 8, pinyin: 'téng yún jià wù', word: '腾云驾雾', hint: '___' },
  { unit: 8, pinyin: 'chéng kòng', word: '程控', hint: '___电话' },
  { unit: 8, pinyin: 'guī gēn dào dǐ', word: '归根到底', hint: '___' },
  { unit: 8, pinyin: 'xīn xǐ ruò kuáng', word: '欣喜若狂', hint: '___' },
  { unit: 8, pinyin: 'xíng tài gè yì', word: '形态各异', hint: '___' },
  { unit: 8, pinyin: 'yuǎn yáng chuán bó', word: '远洋船舶', hint: '___' },
  { unit: 8, pinyin: 'yòng wǔ zhī dì', word: '用武之地', hint: '___' },
  { unit: 8, pinyin: 'měi wèi jiā yáo', word: '美味佳肴', hint: '___' },
];

const UNIT_NAMES = {
  1: '第一单元 · 自然奇观',
  2: '第二单元 · 观察与发现',
  3: '第三单元 · 童话世界',
  4: '第四单元 · 动物朋友',
  5: '第五单元 · 世界遗产',
  6: '第六单元 · 人间真情',
  7: '第七单元 · 成长故事',
  8: '第八单元 · 科技畅想',
};
